### ISSUE TITLE
Add CR Rabi in Pulse

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-iqx-tutorials#732]
Add a CR Pulse into https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/calibrating_a_qubit.ipynb

**Comment by jaygambetta** [comment]
@dcmckayibm do you still want this -- if so what is the status?

**Comment by dcmckayibm** [comment]
Yes, I think it's important to show how to do a schedule on a U channel. @nkanazawa1989 said he can do it asap.

**Comment by nkanazawa1989** [comment]
I added the experiment. but oscillation is not perfectly calibrated. the purpose is just showing the use case of U channels.
