### ISSUE TITLE
clean up the aer folder

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-iqx-tutorials#764]
- order the notebooks
- update the 1_start_here file to have them all. 
- I think we should add a stabilizer simulator example before the extended stabilizer.

**Comment by nonhermitian** [comment]
Addressed in #771

**Comment by jaygambetta** [comment]
just got the stabilizer simulator to go. Happy to close and make a new issue. This should go before the extended.

**Comment by nonhermitian** [comment]
Closing this as done.  Feel free to bring up stabalizer in new pr
