### ISSUE TITLE
Interactive tutorials not working

### ISSUE THREAD

**Issue by trsh** [Qiskit/qiskit-iqx-tutorials#789]
https://mybinder.org/v2/gh/qiskit/qiskit-tutorials/master?filepath=./qiskit/start_here.ipynb

404 not found

**Comment by nonhermitian** [comment]
Binder has been removed in favor of the IQX: https://quantum-computing.ibm.com/

Once you have an account: https://quantum-computing.ibm.com/jupyter/tutorial/1_start_here.ipynb

**Comment by trsh** [comment]
@nonhermitian  the issue should not be closed after link is fixed in readme?

**Comment by omarcostahamido** [comment]
#790 fixes this
