### ISSUE TITLE
Missing '%matplotlib inline' on several notebooks

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-iqx-tutorials#821]
### Informations

- **Qiskit version**: 0.12.1
- **Python version**: 3.7.4
- **Operating system**: macOS Mojave v10.14.6

### What is the current behavior?

Matplotlib figures do not get plotted unless local ipython configuration files contain the instruction to make `matplotlib = "inline"`. The affected notebooks (inline required but not present) are:

- [ ] ./qiskit/fundamentals/2_plotting_data_in_qiskit.ipynb
- [ ] ./qiskit/advanced/terra/2_operators_overview.ipynb
- [ ] ./qiskit/advanced/terra/3_advanced_circuit_visualization.ipynb
- [x] ./qiskit/advanced/terra/4_transpiler_passes_and_passmanager.ipynb
- [ ] ./qiskit/advanced/aer/1_aer_provider.ipynb
- [x] ./qiskit/advanced/aer/2_device_noise_simulation.ipynb
- [ ] ./qiskit/advanced/aer/3_building_noise_models.ipynb
- [ ] ./qiskit/advanced/aer/4_custom_gate_noise.ipynb
- [ ] ./qiskit/advanced/aer/6_extended_stabilizer_tutorial.ipynb
- [ ] ./qiskit/advanced/ignis/1_calibrating_a_qubit.ipynb
- [ ] ./qiskit/advanced/ignis/4_measurement_error_mitigation.ipynb
- [ ] ./qiskit/advanced/ignis/5a_randomized_benchmarking.ipynb
- [ ] ./qiskit/advanced/ignis/5b_interleaved_rb.ipynb
- [ ] ./qiskit/advanced/ignis/5c_purity_rb.ipynb
- [ ] ./qiskit/advanced/ignis/7_quantum_volume.ipynb
- [ ] ./qiskit/advanced/aqua/artificial_intelligence/qsvm_classification.ipynb
- [ ] ./qiskit/advanced/aqua/finance/simulation/credit_risk_analysis.ipynb
- [ ] ./qiskit/advanced/aqua/optimization/vehicle_routing.ipynb

### Steps to reproduce the problem

Reset the ipython configuration files if necessary and run any affected notebook.

### What is the expected behavior?

Figures should show up when the notebooks are run.

### Suggested solutions

- [ ] Add the `%matplotlib inline` magic to the beginning of the affected notebooks.
- [ ] Include a brief reference to this behavior in **./qiskit/fundamentals/2_plotting_data_in_qiskit.ipynb**.
- [ ] Include a note on how to set the ipython local configuration files [(stackoverflow)](https://stackoverflow.com/questions/21176731/automatically-run-matplotlib-inline-in-ipython-notebook) in **./qiskit/fundamentals/2_plotting_data_in_qiskit.ipynb** and/or **./qiskit/advanced/terra/3_advanced_circuit_visualization.ipynb**.

**Comment by nonhermitian** [comment]
It is technically not needed anymore on recent releases of Jupyter.

**Comment by pedrorrivero** [comment]
Great news! Thank you for the update. I am closing this issue then, feel free to reopen if necessary.
