### ISSUE TITLE
plot_state_qsphere- ModuleNotFoundError: No module named 'seaborn'

### ISSUE THREAD

**Issue by ProgrammingVibes** [Qiskit/qiskit-iqx-tutorials#832]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3.7.4
- **Operating system**: Windows 10

### What is the current behavior?
In "2_plotting_data_in_qiskit.ipynb", plot_state_qsphere(psi) hits the following error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\Qiskitenv\lib\site-packages\qiskit\visualization\state_visualization.py in plot_state_qsphere(rho, figsize, ax)
    560     try:
--> 561         import seaborn as sns
    562     except ImportError:

ModuleNotFoundError: No module named 'seaborn'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-28-49f76c353ad1> in <module>
----> 1 plot_state_qsphere(psi)

C:\ProgramData\Anaconda3\envs\Qiskitenv\lib\site-packages\qiskit\visualization\state_visualization.py in plot_state_qsphere(rho, figsize, ax)
    561         import seaborn as sns
    562     except ImportError:
--> 563         raise ImportError('Must have seaborn installed to use '
    564                           'plot_state_qsphere')
    565     rho = _validate_input_state(rho)

ImportError: Must have seaborn installed to use plot_state_qsphere
```

### Steps to reproduce the problem
1)Run every section in order on "2_plotting_data_in_qiskit.ipynb" Jupyter Notebook.
2)Issue will be hit in section [28]: ```plot_state_qsphere(psi)```

### What is the expected behavior?
A diagram should be outputted.

### Suggested solutions
Include relevant seaborn dependancies in Qiskit library

**Comment by Renaller** [comment]
You have to install the Python seaborn package. 

Run `pip install seaborn` in your terminal and then restart your kernel in your Jupyter notebook. Finally, before using `plot_state_qsphere()` import seaborn via `import seaborn as sns` for example.

Had the same issue and this solve it for me.

https://seaborn.pydata.org/

**Comment by nonhermitian** [comment]
This has been fixed in the latest version of Qiskit
