### ISSUE TITLE
AQT device doesn't work

### ISSUE THREAD

**Issue by peachnuts** [Qiskit/qiskit-iqx-tutorials#839]
I tried to execute the examples from
[7_different_qubit_technologies.ipynb](url)

When I executed aqt_provider.backends(),
Why did I only find the aqt device 'aqt_innsbruck' without the 'aqt_qasm_simulator'?
Then I tried the first example 'standard GHZ state',
there was always some errors.
![image](https://user-images.githubusercontent.com/35613442/70255076-75585080-1786-11ea-9bed-a6b8b375605b.png)

How can I solve this problem?
Thanks!

**Comment by peachnuts** [comment]
![image](https://user-images.githubusercontent.com/35613442/70255166-9de04a80-1786-11ea-9d16-aa49063025a9.png)

**Comment by nonhermitian** [comment]
It does now if you sign up for an account with them.
