### ISSUE TITLE
codes from tutorial for solving linear system cannot be run

### ISSUE THREAD

**Issue by Weichen-Xie** [Qiskit/qiskit-iqx-tutorials#860]
### Informations

- **Qiskit version**: 0.14.0
- **Python version**: 3.7.3
- **Operating system**: macOS Catalina Version 10.15.2 (19C57)

### What is the current behavior?
In the tutorial: 
qiskit-iqx-tutorials/qiskit/advanced/aqua/linear_systems_of_equations.ipynb

In [4] cannot be run:
<ipython-input-447-a1017b57671a> in <module>
      1 orig_size = len(vector)
----> 2 matrix, vector, truncate_powerdim, truncate_hermitian = HHL.matrix_resize(matrix, vector)

AttributeError: type object 'HHL' has no attribute 'matrix_resize'

### Steps to reproduce the problem
Copy the codes to Jupiter notebook, and run.

### What is the expected behavior?
According to the tutorial, the codes should output:

solution  [1.05859-0.j 1.99245-0.j]
classical solution  [1. 2.]
probability 0.024630
fidelity 0.999389

### Suggested solutions
I do not know how to solve the problem...
I tried to set the following inputs, but it didn't work and python shut down by itself...

In [3]:
matrix = np.array([[1,0],[0,2]])
vector = np.array([1,4])

In[4]: (the rest of the codes are unchanged)
orig_size = len(vector)
truncate_powerdim = False
truncate_hermitian = False
...

Result of In[4]:
---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-448-f5f148685fe7> in <module>
      4 
      5 # Initialize eigenvalue finding module
----> 6 eigs = create_eigs(matrix, 3, True)
      7 num_q, num_a = eigs.get_register_sizes()
      8 

<ipython-input-432-c6e88fc71b00> in create_eigs(matrix, num_ancillae, negative_evals)
     13                    evo_time = None,
     14                    negative_evals = negative_evals,
---> 15                    ne_qfts = ne_qfts)
     16 
     17 def fidelity(hhl, ref):

/Library/Python/3.7/site-packages/qiskit/aqua/components/eigs/eigs_qpe.py in __init__(self, operator, iqft, num_time_slices, num_ancillae, expansion_mode, expansion_order, evo_time, negative_evals, ne_qfts)
    113         super().__init__()
    114         super().validate(locals())
--> 115         self._operator = op_converter.to_weighted_pauli_operator(operator)
    116         self._iqft = iqft
    117         self._num_ancillae = num_ancillae

/Library/Python/3.7/site-packages/qiskit/aqua/operators/op_converter.py in to_weighted_pauli_operator(operator)
     80                                [basis for basis in itertools.product(possible_basis, repeat=num_qubits)],
     81                                task_kwargs={"matrix": operator._matrix},
---> 82                                num_processes=aqua_globals.num_processes)
     83         for trace_value, pauli in results:
     84             weight = trace_value * coeff

/Library/Python/3.7/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    132             # Otherwise just reset parallel flag and error
    133             os.environ['QISKIT_IN_PARALLEL'] = 'FALSE'
--> 134             raise error
    135 
    136         Publisher().publish("terra.parallel.finish")

/Library/Python/3.7/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    122                 future = executor.map(_task_wrapper, param)
    123 
--> 124             results = list(future)
    125             Publisher().publish("terra.parallel.done", len(results))
    126 

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    474     careful not to keep references to yielded objects.
    475     """
--> 476     for element in iterable:
    477         element.reverse()
    478         while element:

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.monotonic())

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by woodsp-ibm** [comment]
The tutorials should be run against the latest version of code since they are assured to be compatible with the latest and may not work on older versions - in this case you need the latest Aqua version 0.6.2.

**Comment by Weichen-Xie** [comment]
Thank you~ It works after updating Aqua to 0.6.2!
