### ISSUE TITLE
Some images not displaying when viewed in GitHub

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit-iqx-tutorials#863]
### Informations

- **Qiskit version 0.14.0**:
- **Python version 3.7.4**:
- **MacOS**:

### What is the current behaviour?

When viewing fundamentals Tutorial 4 in GitHub the browser (I tried in Chrome and Safari) the following images do not display:

depth_1.png
depth_2.png
tensor_factors_1.png

As these images appear to be key to understanding concepts explained in the tutorial (such as quantum depth) it would be helpful to be able to see them. The images show fine when the notebooks are run locally but would be a better user experience if they could also be displayed when the tutorial is viewed in GitHub.

### Steps to reproduce the problem

view fundamentals tutorial 4 in Github:
https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/fundamentals/4_quantum_circuit_properties.ipynb

### What is the expected behaviour?

Images should be displayed correctly regardless of how the tutorials are accessed.

### Suggested solutions

I'm not familiar with image rendering on GitHub but perhaps this is an issue with how the png is referenced in markdown?

If this is an issue for Tutorial 4 it may also be an issue in others.

**Comment by nonhermitian** [comment]
It is due to the limitations of github rendering of notebooks that is outside of our control. Alternatively use nbviewer:

https://nbviewer.jupyter.org/github/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/fundamentals/4_quantum_circuit_properties.ipynb

**Comment by javabster** [comment]
Ah I see, that's a shame but oh well, I'll close the issue
